# Generated by Django 4.2.20 on 2025-03-08 07:38

from django.db import migrations, models
import utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(unique=True)),
                ('short_url', models.CharField(default=utility.get_random_string_for_url, editable=False, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
